 mongo:
  #image: aeon/mongodb
  container_name: "mongo"
  build: ../src/platform/env/mongodb
  ports:
  - "27017:27017"
 rabbitmq:
  image: rabbitmq
  container_name: "rabbitmq"
  ports:
   - "5672:5672"
   - "15672:15672"
 events:
  container_name: "events"
  #image: aeon/eventsmanager
  build: ../src/platform/events-manager
  ports:
   - "7789:7789"
  links:
   - mongo
   - rabbitmq
 dashboard:
  container_name: "dashboard"
  #image: aeon/dashboard
  build: ../src/platform/frontend
  ports:
   - "8080:8000"
 rest:
  container_name: "rest"
  #image: aeon/backend
  build: ../src/platform/rest
  ports:
   - "3000:3000"
  links:
   - mongo
   - rabbitmq
   - events
   - dashboard
  extra_hosts:
   - "docker_host: 192.168.59.103"
